name: binance post

# 【检出（Checkout）该仓库的代码】我们提交了这个工作流，它应该会「自动运行」，因为工作流中默认设置触发条件。
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # # 【定时任务】Cron 表达式 0 * * * * 表示每小时 0 分触发一次。对 Cron 表达式不熟悉的读者，可以参考 Cron Guru。
  #   - cron:  '*/30 * * * *'表示30秒执行一次任务
  #   - cron:  '0 * * * *'表示每小时 0 分触发一次
  schedule:
  #   - cron:  '0 * * * *'
    - cron:  '*/30 * * * *'
permissions:
  contents: read

jobs:
  build:
    # 设置服务器系统版本
    runs-on: ubuntu-latest

    # 设置 Python 运行环境
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # 安装依赖
    - name: Install dependencies
      run: |
        cd actions/github-actions-python
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # 运行程序
    - name: Run
      run: |
        cd actions/github-actions-python
        python main.py
